### ISSUE TITLE
Not working plugin

### ISSUE THREAD

**Issue by onlive1337** [tddebart/Steam-SteamDB-extension#10]
idk why but plugin doesn't work for me
![image](https://github.com/user-attachments/assets/eb4b68fc-b6d3-4a88-8e4c-bb93f0acb152)

**Comment by tddebart** [comment]
Have you fully restarted the steam client after enabling it?
if you have can you then upload your log file which is in `{steamDirectory}/ext/data/logs/debug.log`, this will help with troubleshooting.

**Comment by onlive1337** [comment]
[debug.log](https://github.com/user-attachments/files/18241553/debug.log)
here

**Comment by tddebart** [comment]
Hmm, from what i see from the log is that you booted steam without it enabled and then enabled it, which doesn't work.
You need to FULLY restart steam AFTER enabling it for it to work.

**Comment by onlive1337** [comment]
after restarting pc it works
