### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by XDR46ON** [tddebart/Steam-SteamDB-extension#2]
Doesn't work for me.
SteamDB v1.0.2
Milenium v2.15.0
Window 10 
Steam client, up to date, doesn't work neither with the beta nor the stable release. 

SteamDB is active in the Steam Millennium extension, but the store page is the same as before.
No option for SteamDB in my store preference, either.

**Comment by tddebart** [comment]
This currently requires the latest "beta" version of millenium version 2.16.0 which can be downloaded from here https://github.com/shdwmtr/millennium/actions/runs/12058248256.  
  
I also updated the readme and release to make it clearer which version is needed. Thanks for the super clear report.
Let me know if it still doesn't work after this.

**Comment by XDR46ON** [comment]
> This currently requires the latest "beta" version of millenium version 2.16.0 which can be downloaded from here https://github.com/shdwmtr/millennium/actions/runs/12058248256.

Thank you for the quick response.
Doesn't work either after installing manually the beta v2.16.0 from the link.

**Comment by XDR46ON** [comment]
> Hmm weird, you might need to disable auto update. 
I think I simply wait for a stable realize. 

The log report this error multiple time : 
`ERROR failed to open file -> C:\Gama Files\Steam\plugins\SteamDB-plugin/.millennium/Dist/index.js`

[debug.log](https://github.com/user-attachments/files/17969385/debug.log)

**Comment by XDR46ON** [comment]
It's worse with the v1.0.3, Steam doesn't even start…

**Comment by tddebart** [comment]
makes sense as in v1.0.3 I'm using the  `__file__` path in the backend to copy some files which freezes up millennium in 2.15.0.
Best to just wait until 2.16.0 releases.

**Comment by tddebart** [comment]
Millennium 2.16 has released, can you test if it works now?

**Comment by XDR46ON** [comment]
> Millennium 2.16 has released, can you test if it works now?

Looks good.
No bug so far.
