### ISSUE TITLE
"Debugger paused in another tab, click to switch to that tab"

### ISSUE THREAD

**Issue by KratoZenk** [tddebart/Steam-SteamDB-extension#5]
![image](https://github.com/user-attachments/assets/d1a3d357-79d0-4e6f-b0f0-9f5e233053f7)
It either shows this when im trying to login while using the plugin or the ui just completely freezes. Everything works fine without the plugin using millenium. I am using the beta specified in the install instructions also.

**Comment by tddebart** [comment]
I can't seem to reproduce this, best to just wait until millennium 2.16 fully releases and then try again.

**Comment by painfulbunny** [comment]
Yeah I had the same issue. It went away but just won't work. I'm waiting for the stable release.

**Comment by tddebart** [comment]
Millennium 2.16 has released, can you test if it is fixed now?
