### ISSUE TITLE
having the plugin in the folder make the port 8080 problem

### ISSUE THREAD

**Issue by CODEX0827** [tddebart/Steam-SteamDB-extension#8]
having the plugin in the folder make the port 8080 problem
I guess the plugin need an update

**Comment by tddebart** [comment]
I don't think that is correct as this plugin does nothing with ports, so that would be an issue with millennium then. Closing this.

**Comment by CODEX0827** [comment]
If i reopen steam it this plugin enabled I get the port 8080 problem and if i remove it then millennium is working dont know what else I need to as

also when i have it on it just not working for me
