### ISSUE TITLE
[bug] SteamDB.info blank page

### ISSUE THREAD

**Issue by FleXi2108** [tddebart/Steam-SteamDB-extension#9]
Whenever SteamDB asks me to verify that I'm human it returns a black page after checking the box

https://github.com/user-attachments/assets/04d6b3ad-6e51-456b-80eb-64fc05c5e790

**Comment by QARDEP** [comment]
+1 I have the same issue

**Comment by tddebart** [comment]
New update of millennium has been out for a moment and seems to fully fix this. Closing this issue.
